---
abstract: 'PSGI middleware to highlight text in an HTML response'
author:
  - 'Lee Aylward <leedo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Request: 0
  Plack::App::File: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Highlighter
no_index:
  directory:
    - inc
    - share
    - t
requires:
  HTML::Parser: 0
  Plack: 0
  Plack::Request: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
